# name: CI/CD pipeline for Docker

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Build and push
#         uses: docker/build-push-action@v6
#         with:
#           platforms: linux/amd64,linux/arm64
#           push: true
#           tags: ramanath17/new-nodejs-app:latest


name: CI/CD Pipeline for Docker

# Trigger workflow on push to main or when creating a pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx (to enable multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ramanath17/new-nodejs-app:latest .

      # Push the Docker image to Docker Hub (or any container registry)
      - name: Push Docker image to Docker Hub
        run: |
          docker push ramanath17/new-nodejs-app:latest

      # Optional: Add deployment steps here if needed
